apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: still-barracuda-python 
  janus-idp.io/tekton: still-barracuda-python
  backstage.io/kubernetes-id: still-barracuda-python
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: still-barracuda-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  