apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: still-barracuda-python-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/still-barracuda-python-gitops